version: '3.8'
services:
  server:
    build: 'server'
    restart: always
    ports:
      - '127.0.0.1:1031:1031'
    networks:
      - mytime-app
  client:
    build: 'client'
    ports:
      - '127.0.0.1:1030:80'
    networks:
      - mytime-app
    depends_on:
      - server
networks:
  mytime-app:
    driver: bridge
